<section class="well1 well1_ins center sct-link-top" id="gallery"><a class="fa-arrow-down nav-link" href="index.html#contacts" data-custom-scroll-to="contacts"></a>
    <h2>Gallery</h2>
    <div class="gallery" data-lightgallery="group">
        <div class="gallery-row">
            <div class="block">
                <div class="wdth"><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img05_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img05.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img11_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img11.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a></div>
                <div class="wdth-dob"><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img06_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img06.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a></div>
                <div class="wdth-dob clear"><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img15_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img15.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a></div>
                <div class="wdth"><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img16_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img16.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img22_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img22.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a></div>
            </div>
            <div class="block1">
                <div class="wdth"><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img07_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img07.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img12_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img12.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a></div>
                <div class="wdth"><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img08_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img08.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img13_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img13.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a></div>
                <div class="wdth-dob"><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img17_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img17.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a></div>
            </div>
            <div class="block">
                <div class="wdth-dob"><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img09_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img09.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a></div>
                <div class="wdth"><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img10_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img10.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img14_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img14.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a></div>
                <div class="wdth clear"><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img18_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img18.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img20_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img20.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a></div>
                <div class="wdth-dob"><a class="thumb" data-lightgallery="item" href="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img19_original.jpg"><img src="https://livedemo00.template-help.com/wt_prod-20484/images/page-1_img19.jpg" alt=""><span class="thumb_overlay">ZOOM</span></a></div>
            </div>
        </div>
    </div>
</section>
