@extends('index')
@section('banner')
    @include('content.general_content.banner')
@endsection
@section('content')
    @include('content.general_content.video')
    @include('content.general_content.counters')
    @include('content.general_content.what_we_offer')
    @include('content.general_content.services')
    @include('content.general_content.about_us')
    @include('content.general_content.gallery')
    @include('content.general_content.social')
    @include('content.general_content.contact')
@endsection
